export const img = (id, w = 1600) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=84`;

export const siteImages = {
  hero: img("photo-1507525428034-b723cf961d3e", 2200),
  story: img("photo-1600607687939-ce8a6c25118c", 1400),
  introStory: img("photo-1582268611958-ebfd161ef9cf", 1400),
  islands: img("photo-1510414842594-a61c69b5ae57"),
  villas: img("photo-1600607687920-4e2a09cf159d"),
  aviation: img("photo-1540962351504-03099e0a754b"),
  yachts: img("photo-1544551763-46a013bb70d5"),
  maldives: img("photo-1514282401047-d79a71a590e8"),
  seychelles: img("photo-1589979481223-deb893043163"),
  mauritius: img("photo-1590080875515-8a3a8dc5735e"),
  greece: img("photo-1533104816931-20fa691ff6ca"),
  italy: img("photo-1533105079780-92b9be482077"),
  france: img("photo-1502602898657-3e91760cbb34"),
  switzerland: img("photo-1527668752968-14dc70a27c95"),
  turkey: img("photo-1524231757912-21f4fe3a7200"),
  dubai: img("photo-1512453979798-5ea266f8880c"),
  thailand: img("photo-1552465011-b4e21bf6e79a"),
  bali: img("photo-1533669955142-6a73332af4db"),
  europe: img("photo-1499856871958-5b9627545d1a"),
  beyond: img("photo-1464822759023-fed622ff2c3b"),
  property1: img("photo-1540202404-a2f29016b523"),
  property2: img("photo-1573843981267-be1999ff37cd"),
  property3: img("photo-1544550285-f813152fb2fd"),
  property4: img("photo-1539367628448-4bc5c9d171c8"),
  gallery1: img("photo-1573843981267-be1999ff37cd", 1100),
  gallery2: img("photo-1499793983690-e29da59ef1c2", 1100),
  gallery3: img("photo-1540202404-a2f29016b523", 1100)
};

const d = (slug, title, arTitle, tagline, arTagline, intro, arIntro, places, stays, ideas, itinerary, suits, planning, image, janaTravelUrl = null) => ({
  slug, title, arTitle, tagline, arTagline, intro, arIntro, places, stays, ideas, itinerary, suits, planning, image: image || siteImages[slug], janaTravelUrl,
  faqs: [
    ["How is a Jana journey planned?", "We begin with your pace, priorities and preferred style of stay, then confirm every proposed element with the relevant supplier."],
    ["Is the sample itinerary fixed?", "No. It is an illustrative starting point; routing, properties and experiences remain subject to your brief and confirmed availability."],
    ["Can this destination be combined with another?", "Often, yes. We will assess sensible connections and present a coherent route rather than simply adding stops."]
  ]
});

export const destinations = [
  d("maldives", "Maldives", "المالديف", "Private islands. Endless horizons.", "جزر خاصة وآفاق بلا نهاية.", "A constellation of coral atolls where each island has its own rhythm. Within the JANA Luxury Collection, the Maldives is presented as a selective editorial lens—private islands, exceptional resorts, extraordinary residences and bespoke experiences shaped around how you wish to travel, not a catalogue to browse.", "سلسلة من الجزر المرجانية، لكل جزيرة إيقاعها الخاص. في مجموعة جنى الفاخرة، تُقدَّم المالديف كمنظور تحريري انتقائي—جزر خاصة ومنتجعات استثنائية ومساكن فاخرة وتجارب مصممة حول طريقة سفركم، لا كقائمة للتصفح.", ["North & South Malé Atolls", "Raa Atoll", "Noonu Atoll", "Baa Atoll"], ["Overwater pool villas", "Beach residences", "Private-island buyouts"], ["House-reef snorkelling", "Private sandbank dining", "Marine discovery", "Restorative wellness"], ["Arrive and settle into island time", "Two unhurried ocean days", "A private water or dining experience", "A final day reserved for rest"], "Couples, families and groups seeking privacy, warm-water days and a stay where the resort itself is the destination.", "Island access varies by resort and may involve speedboat, seaplane or domestic connections. We confirm the appropriate transfer, baggage conditions and current entry requirements before booking.", null, "https://jana.travel/maldives"),
  d("seychelles", "Seychelles", "سيشل", "Untouched beauty.", "جمال على طبيعته.", "Granite coves, forested interiors and quiet Indian Ocean shores give the Seychelles a rare, elemental beauty. The Luxury Collection view is selective: island character, private residences and unhurried days shaped personally—not a repeat of the full destination guide.", "خلجان جرانيتية وغابات استوائية وشواطئ هادئة تمنح سيشل جمالاً فريداً. يركز منظور المجموعة الفاخرة على طابع الجزر والمساكن الخاصة والأيام الهادئة المصممة شخصياً—لا على تكرار دليل الوجهة الكامل.", ["Mahé", "Praslin", "La Digue", "Private outer islands"], ["Clifftop villas", "Beach resorts", "Exclusive-use island retreats"], ["Creole food discoveries", "Sailing between islands", "Nature walks", "Quiet beach days"], ["Begin on Mahé", "Continue to a smaller island", "Set aside a day on the water", "Close with two slow beach days"], "Travellers drawn to nature, island-hopping and a more textured alternative to a single-resort stay.", "Inter-island arrangements depend on route, weather and supplier schedules. We verify current access and keep the sequence comfortably paced.", null, "https://jana.travel/seychelles"),
  d("mauritius", "Mauritius", "موريشيوس", "Island living, elevated.", "حياة الجزيرة بلمسة راقية.", "Mauritius pairs polished coastal resorts with a mountainous, culturally layered interior. Here, the Luxury Collection introduces the island as a curated starting point—coastal ease, private residences and discovery days arranged with restraint.", "تجمع موريشيوس بين المنتجعات الساحلية الراقية والجبال والثقافة المتنوعة. هنا تقدّم المجموعة الفاخرة الجزيرة كنقطة انطلاق مدروسة—هدوء ساحلي ومساكن خاصة وأيام اكتشاف بإيقاع متزن.", ["Le Morne", "Black River", "Belle Mare", "The central highlands"], ["Beach suites", "Family villas", "Golf and wellness resorts"], ["Lagoon sailing", "Botanical gardens", "Creole cooking", "Mountain landscapes"], ["Settle on the coast", "Explore the south-west", "A private lagoon day", "A restorative final chapter"], "Families, active couples and longer-stay travellers wanting variety without frequent hotel changes.", "The island is larger than it first appears. We consider drive patterns, preferred coast and daily interests before choosing a base.", null, "https://jana.travel/mauritius"),
  d("greece", "Greece", "اليونان", "The Mediterranean, privately.", "المتوسط بخصوصية تامة.", "Whitewashed islands, storied cities and a coastline made for private sailing. Greece is best shaped around contrast: one vivid cultural stop and one or two places to exhale.", "جزر بيضاء ومدن عريقة وساحل مثالي للإبحار الخاص. تتشكل أجمل رحلات اليونان من التباين بين الثقافة والهدوء.", ["Athens & the Riviera", "Cyclades", "Ionian islands", "Crete & the Peloponnese"], ["Clifftop suites", "Private island villas", "Restored rural estates"], ["After-hours cultural visits", "Private sailing", "Village tables", "Hidden-cove swimming"], ["An Athens arrival", "One island with character", "A private day at sea", "A second, slower island"], "Couples, friends and multigenerational groups who enjoy food, design, history and the sea in equal measure.", "Ferry, flight and yacht plans are highly seasonal. We verify the operating schedule and avoid rushed same-day connections."),
  d("italy", "Italy", "إيطاليا", "La Dolce Vita, your way.", "لا دولتشي فيتا بطريقتك.", "Italy invites a journey built around taste: art, landscape, food and a beautifully chosen place to stay. The challenge is not what to include, but what to leave space to enjoy.", "تدعو إيطاليا إلى رحلة تُبنى حول الذوق والفن والمناظر والطعام والإقامة المختارة بعناية، مع مساحة كافية للاستمتاع بكل لحظة.", ["Rome & Florence", "Amalfi Coast", "Tuscany", "The Italian lakes"], ["Historic palazzi", "Countryside estates", "Lake and coastal villas"], ["Private art access", "Market-to-table cooking", "Vintage drives", "Days on the water"], ["A city immersion", "A countryside pause", "A privately guided art day", "A coast or lake finale"], "Curious travellers who prize food, culture, craft and character-rich accommodation.", "Opening days, local traffic rules and seasonal access can shape the route. We reconfirm all time-sensitive details for your travel dates."),
  d("france", "France", "فرنسا", "Timeless elegance.", "أناقة خالدة.", "From Parisian ateliers to Riviera light and vineyard landscapes, France makes room for both ceremony and spontaneity. We design the journey around a strong sense of place.", "من مشاغل باريس إلى ضوء الريفييرا وكروم العنب، تتيح فرنسا مساحة للأناقة والعفوية معاً في رحلة ذات إحساس واضح بالمكان.", ["Paris", "Provence", "French Riviera", "Bordeaux & Burgundy"], ["Palace hotels", "Private bastides", "Wine-country châteaux"], ["Private collections", "Chef-led markets", "Estate tastings", "Riviera cruising"], ["Paris with private context", "A rail or road transition", "Three nights in the countryside", "A relaxed Riviera finish"], "Design-minded couples, families and repeat visitors who want privileged context without an overfilled diary.", "Restaurant and cultural access may require advance planning. Seasonal closures and event calendars are checked before confirmation."),
  d("switzerland", "Switzerland", "سويسرا", "Alpine excellence.", "تميّز جبال الألب.", "Precise, serene and spectacular, Switzerland combines grand alpine hotels with lakefront calm and beautifully connected journeys through changing landscapes.", "دقة وهدوء ومناظر آسرة؛ تجمع سويسرا بين فنادق الألب العريقة وسكينة البحيرات ورحلات سلسة عبر مناظر متبدلة.", ["The Bernese Oberland", "Engadin", "Lake Geneva", "Lucerne"], ["Grand alpine hotels", "Ski-in residences", "Lakefront retreats"], ["Scenic rail journeys", "Private mountain guides", "Lake cruises", "Wellness and winter sport"], ["Arrive beside a lake", "Travel into the Alps", "A guided landscape day", "Two days at your own pace"], "Families, active travellers and anyone who values discreet service, clean design and effortless logistics.", "Mountain conditions and lift or rail operations are seasonal. We verify current services and build alternatives into weather-dependent days."),
  d("turkey", "Turkey", "تركيا", "A meeting of worlds.", "ملتقى العوالم.", "Turkey moves from the waterways and layered history of Istanbul to the Aegean coast and the otherworldly landscapes of Cappadocia.", "تنتقل تركيا من مضائق إسطنبول وتاريخها المتعدد إلى ساحل إيجه ومناظر كابادوكيا الاستثنائية.", ["Istanbul", "Bodrum & the Aegean", "Cappadocia", "The Turquoise Coast"], ["Bosphorus hotels", "Aegean villas", "Cave-inspired retreats"], ["Private museum context", "Gulet cruising", "Artisan workshops", "Landscape walks"], ["Three nights in Istanbul", "A change of landscape", "A private cultural day", "A coast-led final chapter"], "Travellers looking for history, generous food culture, design and a rewarding city-to-coast journey.", "Domestic routing, opening days and coastal seasons affect the shape of a trip. Current entry requirements must be checked for each traveller."),
  d("dubai", "Dubai", "دبي", "Desert energy. Coastal ease.", "طاقة الصحراء وهدوء الساحل.", "Dubai brings ambitious architecture, a global dining scene, warm-water coast and desert landscapes into one highly adaptable stay.", "تجمع دبي بين العمارة الطموحة والمطاعم العالمية والساحل الدافئ والصحراء في إقامة واحدة قابلة للتخصيص.", ["Jumeirah", "Downtown", "Dubai Creek & Al Fahidi", "The desert conservation landscape"], ["Beach resorts", "Skyline suites", "Private urban residences"], ["Private architecture tours", "Desert conservation outings", "Creek and heritage walks", "Chef-led dining"], ["A waterfront arrival", "Old Dubai with context", "A desert afternoon", "A day shaped around food or design"], "Stopover guests, families and travellers who appreciate choice, comfort and a city that can shift pace quickly.", "Heat, cultural calendars and major events may affect timings. We plan around the season and verify current venue access."),
  d("thailand", "Thailand", "تايلاند", "Culture, coast and generous spirit.", "ثقافة وساحل وروح مضيافة.", "Thailand rewards a layered route: Bangkok's vivid energy, a quieter cultural north and a coast chosen for the season and style of travel.", "تكافئ تايلاند المسافر بمسار متنوع يجمع حيوية بانكوك وهدوء الشمال الثقافي وساحلاً مختاراً بعناية.", ["Bangkok", "Chiang Mai", "Phuket & Phang Nga", "Koh Samui"], ["Riverside hotels", "Pool villas", "Island hideaways"], ["Temple and design walks", "Regional cooking", "Private boat days", "Forest wellness"], ["Two nights in Bangkok", "A cultural change of pace", "Fly to the right coast", "Three unstructured island days"], "Food lovers, families and first-time Asia travellers who want a rich journey balanced with a restorative beach stay.", "Coast choice depends on travel dates and current conditions. We verify transfers, local advisories and entry rules close to booking."),
  d("bali", "Bali", "بالي", "Ritual, landscape and renewal.", "طقوس وطبيعة وتجدد.", "Bali's appeal lies beyond the coast: temple landscapes, craft traditions, rice terraces and a deeply rooted culture of ceremony and hospitality.", "يمتد سحر بالي إلى ما وراء الساحل، في المعابد والحرف ومدرجات الأرز وثقافة الضيافة والطقوس المتجذرة.", ["Ubud", "Uluwatu", "Canggu & the south-west", "East Bali"], ["Jungle pool villas", "Clifftop retreats", "Design-led private residences"], ["Temple visits with context", "Studio and craft encounters", "Water purification rituals", "Surf and coastal days"], ["Begin inland", "Meet makers and guides", "Move to the coast", "Leave one day entirely open"], "Wellness seekers, creative travellers and couples who enjoy meaningful culture alongside beautiful design.", "Traffic can materially affect a day. We select bases carefully, allow realistic pacing and confirm the respectful dress or conduct required at sacred sites."),
  d("europe", "Europe", "أوروبا", "Many worlds, one considered journey.", "عوالم متعددة في رحلة واحدة مدروسة.", "Europe is not one itinerary. It is a collection of distinct cultures and landscapes best connected with restraint, choosing fewer places and experiencing them more deeply.", "أوروبا ليست مساراً واحداً، بل ثقافات ومناظر متباينة تُكتشف على مهل مع اختيار محطات أقل وتجارب أعمق.", ["Mediterranean coasts", "Alpine landscapes", "Capital cities", "Countryside estates"], ["Historic hotels", "Private villas", "Remote design retreats"], ["Art and architecture", "Food and wine", "Rail and road journeys", "Private time on the water"], ["Begin with one cultural anchor", "Travel overland where it adds meaning", "Pause in the countryside", "Finish in a restorative setting"], "Travellers wanting a coherent multi-country journey rather than a checklist of capitals.", "Border rules, rail schedules and seasonal openings change. Every proposed connection and requirement is rechecked for your dates.", siteImages.europe),
  d("beyond", "Beyond", "ما وراء الوجهات", "The journey that begins with you.", "رحلة تبدأ بك.", "Beyond is our invitation to begin without a catalogue. Tell us the landscape, feeling or occasion you have in mind and we will research a responsible, well-connected journey outside our featured destinations.", "دعوة للبدء من دون قائمة جاهزة. شاركونا المشهد أو الشعور أو المناسبة، وسنبحث لكم عن رحلة مسؤولة ومترابطة خارج وجهاتنا المختارة.", ["A landscape you have imagined", "A celebration with meaning", "A route led by culture", "A place to be entirely still"], ["Selected only after your brief", "Independently assessed options", "No assumed catalogue"], ["Private research", "Considered routing", "Specialist local context", "Time left unprogrammed"], ["Share the idea", "We research credible possibilities", "Review a first journey shape", "Confirm only after supplier checks"], "Experienced travellers, open-minded families and anyone whose best trip begins with a feeling rather than a pin on a map.", "Nothing on this page suggests a confirmed property catalogue. Recommendations, services and access are researched and verified for each enquiry.", siteImages.beyond)
];

export const services = [
  { slug:"private-islands", title:"Private Islands", arTitle:"الجزر الخاصة", tagline:"Your world. Entirely yours.", image:siteImages.islands, intro:"Privacy means different things to different travellers. We distinguish a secluded island-resort stay from a genuine exclusive-island buyout, then shape the enquiry around space, service and the people travelling with you.", types:["A private villa within an island resort", "A private-island residence", "An exclusive island buyout for family or friends"], consider:["Guest ages and room relationships", "Desired degree of exclusivity", "Access and luggage needs", "Dining, staffing and privacy preferences"] },
  { slug:"private-villas", title:"Private Villas", arTitle:"الفلل الخاصة", tagline:"Exceptional homes in extraordinary places.", image:siteImages.villas, intro:"The right residence gives a group room to be together and space to step away. We source beachfront, countryside and urban villas around your preferred setting, layout and service style.", types:["Beachfront residences", "Countryside estates", "Ski and lake homes", "Design-led city residences"], consider:["Bedroom configuration", "Accessibility and child-friendly needs", "Chef, housekeeping or host services", "Pool, beach and transport preferences"] },
  { slug:"private-aviation", title:"Private Aviation", arTitle:"الطيران الخاص", tagline:"The world, on your schedule.", image:siteImages.aviation, intro:"Jana Travel can coordinate an aviation enquiry with qualified third-party operators and brokers. We do not claim an owned fleet, operating licence, guaranteed access or aircraft availability.", types:["Point-to-point charter enquiries", "Multi-sector journey planning", "Group and family requirements", "Airport and ground-transfer coordination"], consider:["Preferred route and timings", "Passenger numbers", "Luggage volume and special items", "Aircraft options assessed by an authorised provider"] },
  { slug:"private-yachts", title:"Private Yachts", arTitle:"اليخوت الخاصة", tagline:"A different perspective on the world.", image:siteImages.yachts, intro:"A yacht enquiry begins with the region, party and pace—not an invented inventory list. We coordinate the brief with established charter specialists, with all vessels, crews, pricing and availability confirmed by the supplier.", types:["Day-charter concepts", "Crewed coastal charters", "Multi-day island itineraries", "Yacht support for a villa stay"], consider:["Cruising region and preferred dates", "Group size and cabin needs", "Onboard food and activity preferences", "Weather, routing and supplier confirmation"] },
  { slug:"experiences", title:"Experiences", arTitle:"التجارب", tagline:"Moments with meaning.", image:siteImages.story, intro:"The best experiences belong to their setting. We propose ideas with cultural care and leave room for spontaneity; every guide, venue and activity remains subject to destination and supplier confirmation.", types:["Food and culture", "Wellness and renewal", "Ocean and nature", "Celebrations and family travel"], consider:["Energy and accessibility", "Age suitability", "Cultural context", "Weather and confirmed local availability"] }
];

export const properties = [
  { slug:"waldorf-astoria-maldives-ithaafushi", title:"Waldorf Astoria Maldives Ithaafushi", line:"Maldives | Private Island Living", image:siteImages.property1, location:"Ithaafushi Island, South Malé Atoll, Maldives", intro:"A broad, polished island resort arranged across three islands, with beach, reef and overwater villa styles. Its scale and range make it particularly relevant for families and groups with varied interests.", stay:"Private-pool villas span beach, reef and overwater settings; a separate private-island option is also presented by the resort.", design:"Contemporary, generous and resort-led, with indoor-outdoor living shaped around ocean views.", dining:"The official resort site describes a wide selection of restaurants and bars, alongside a lifestyle spa sanctuary.", experiences:["Marine discovery", "Tennis and padel", "Family activities", "Private-island enquiries"], considerations:"This is a large resort with varied locations. Villa setting, privacy preferences and current transfer arrangements should be discussed before selecting a category.", source:"https://www.hilton.com/en/hotels/mleonwa-waldorf-astoria-maldives-ithaafushi/" },
  { slug:"cheval-blanc-randheli", title:"Cheval Blanc Randheli", line:"Maldives | Contemporary Island Elegance", image:siteImages.property2, location:"Randheli Island, Noonu Atoll, Maldives", intro:"Cheval Blanc Randheli presents a refined, residential take on the Maldives across a group of islands in Noonu Atoll, with architecture closely integrated into the lagoon landscape.", stay:"The Maison offers private-pool villas between greenery and water, including one- and two-bedroom options and a distinct private-island residence.", design:"Architect Jean-Michel Gathy conceived the Maison with natural materials, bespoke furnishings and a calm sense of island space.", dining:"Official material describes French-inflected and international culinary settings, while Spa Cheval Blanc occupies a dedicated island and offers Guerlain rituals.", experiences:["Private sandbank dining", "Watersports", "Art and design", "Tailored wellness"], considerations:"Discuss the desired level of privacy, villa location and whether a private-island residence is appropriate. All experiences require current confirmation.", source:"https://www.chevalblanc.com/en/maison/randheli/" },
  { slug:"joali-maldives", title:"JOALI Maldives", line:"Maldives | Art, Design & Island Life", image:siteImages.property3, location:"Muravandhoo Island, Raa Atoll, Maldives", intro:"An art-immersive island resort in Raa Atoll where artworks, design and family-friendly experiences sit alongside the beach and lagoon setting.", stay:"Beach and overwater villas with pools are joined by larger residences designed for families and groups.", design:"Art is integrated throughout the island, giving the resort a creative identity rather than treating it as decoration alone.", dining:"The official resort site presents several culinary styles, private-dining ideas and the JOALI BEING Cure wellness centre.", experiences:["Interactive art discovery", "Cooking experiences", "Marine activities", "Family programmes"], considerations:"The creative, activity-rich atmosphere may particularly suit travellers who want more than a minimal island retreat. Transfer arrangements must be reconfirmed for the travel dates.", source:"https://www.joali.com/joali-maldives/" },
  { slug:"one-and-only-reethi-rah", title:"One&Only Reethi Rah", line:"Maldives | Iconic. Exclusive. Timeless.", image:siteImages.property4, location:"North Malé Atoll, Maldives", intro:"A well-established private-island resort with a strong sense of space, offering beach and water villas alongside signature residences.", stay:"The official resort presents an extensive collection of beach and water villas, plus larger residences for a more expansive stay.", design:"Laid-back, spacious island living defines the atmosphere, with a balance of privacy and varied resort facilities.", dining:"Official information highlights beachfront and overwater dining, farm-to-table ingredients and a spa focused on tailored therapeutic journeys.", experiences:["Freediving and ocean activity", "Private dining", "Island wellness", "Celebration planning"], considerations:"Its breadth suits mixed-age groups, but location within the island and villa style should be matched carefully to each traveller's priorities.", source:"https://www.oneandonlyresorts.com/reethi-rah" }
];

export const ui = {
  en:{nav:["Destinations","The Collection","Private Villas","Private Aviation","Yachts","Experiences","About"], design:"Design Your Journey", search:"Search", division:"A luxury travel division of Jana Travel"},
  ar:{nav:["الوجهات","المجموعة","الفلل الخاصة","الطيران الخاص","اليخوت","التجارب","من نحن"], design:"صمّم رحلتك", search:"بحث", division:"قسم السفر الفاخر لدى جنى ترافل"}
};
