/**
 * Idempotent seed for Yacht documents (production dataset).
 *
 * Yacht names and objective specifications referenced from public Seven Yachts
 * detail pages (Dubai fleet + international weekly charter pages) as factual
 * reference only. Descriptions are original Private Luxury Holidays copy.
 * No Seven Yachts images or marketing text are imported.
 *
 * Usage (from studio/):
 *   npm run seed:yachts
 *
 * Safe to re-run: deterministic ids (yacht-<slug>), fills blank fields only
 * on existing docs, preserves heroImage/gallery, never deletes unrelated docs.
 */
import {getCliClient} from 'sanity/cli'

const client = getCliClient({apiVersion: '2025-01-01'})

type YachtSeed = {
  slug: string
  name: string
  builder: string
  yachtType?: string
  length: number
  lengthUnit: 'ft' | 'm'
  maxGuests: number
  cabins?: number
  crew?: number
  /** Verified home marina/base only — leave blank when unknown. */
  marina?: string
  /** Broad region for internal use only — not the primary website filter. */
  region?: string
  /** Verified charter/home countries. Prefer multiple entries over inventing one. */
  countries?: string[]
  /** More specific cruising notes when useful. */
  cruisingArea?: string
  yearBuilt?: number
  yearRefit?: number
  displayPriority: number
  enquiryStatus: 'Available' | 'On Request' | 'Enquire'
  startingPrice?: number
  currency?: string
  pricingPeriod: 'hour' | 'day' | 'week' | 'on request'
  minimumBookingHours?: number
  shortDescription: string
  fullDescription: string
  amenities?: string[]
  services: string[]
}

const YACHTS: YachtSeed[] = [
  {
    slug: "spectre",
    name: "Spectre",
    builder: "Azimut",
    yachtType: "Motor Yacht",
    length: 100,
    lengthUnit: "ft",
    maxGuests: 40,
    cabins: 4,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 1,
    enquiryStatus: "On Request",
    startingPrice: 6500,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A 100 ft Azimut suited to polished day charters along the Dubai coastline, with space for a larger private gathering.",
    fullDescription: "Spectre may be arranged on request through our private yacht service for considered day charters from Dubai Harbour. Her length and guest capacity suit celebrations, corporate afternoons and unhurried coastal hours. Routing, crew and timings are confirmed with authorised charter partners; we do not claim ownership or guaranteed availability.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "morrigan",
    name: "Morrigan",
    builder: "Galeon",
    yachtType: "Motor Yacht",
    length: 70,
    lengthUnit: "ft",
    maxGuests: 12,
    cabins: 2,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 2,
    enquiryStatus: "On Request",
    startingPrice: 2500,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A compact Galeon for smaller private parties seeking a quieter Dubai day on the water.",
    fullDescription: "Morrigan is typically considered when a closer, more intimate charter is preferred. Available to arrange on request through our private yacht service, she suits couples and small groups who value composure over scale. All rates and berthing details are reconfirmed for each enquiry.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "reno",
    name: "Reno",
    builder: "Sky Walker",
    yachtType: "Motor Yacht",
    length: 62,
    lengthUnit: "ft",
    maxGuests: 25,
    cabins: 3,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 3,
    enquiryStatus: "On Request",
    startingPrice: 1350,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "An accessible Sky Walker day boat for straightforward Dubai harbour and coastline hours.",
    fullDescription: "Reno offers a practical entry point for private day charter when schedule and simplicity matter. Through Private Luxury Holidays, this yacht may be requested via partner operators; guest numbers, marina and minimum hours are verified before any proposal.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "apex",
    name: "Apex",
    builder: "Sky Walker",
    yachtType: "Motor Yacht",
    length: 63,
    lengthUnit: "ft",
    maxGuests: 25,
    cabins: 3,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 4,
    enquiryStatus: "On Request",
    startingPrice: 1700,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A Sky Walker day charter option with a balanced cabin and deck layout for mid-size groups.",
    fullDescription: "Apex is often assessed for Dubai Harbour charters where a mid-size party needs clear deck space without moving to a larger yacht. Availability and final configuration remain subject to confirmation with authorised partners.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "my-serenity",
    name: "My Serenity",
    builder: "Sunseeker",
    yachtType: "Motor Yacht",
    length: 70,
    lengthUnit: "ft",
    maxGuests: 20,
    cabins: 4,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 5,
    enquiryStatus: "On Request",
    startingPrice: 2500,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A Sunseeker day yacht for composed coastal hours with a refined cabin arrangement.",
    fullDescription: "My Serenity suits travellers who prefer a familiar Sunseeker character for Dubai day charter. She may be arranged on request through our private yacht service, with marina, guest capacity and minimum booking confirmed case by case.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "infinity",
    name: "Infinity",
    builder: "Skywalker",
    yachtType: "Motor Yacht",
    length: 60,
    lengthUnit: "ft",
    maxGuests: 45,
    cabins: 4,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 6,
    enquiryStatus: "On Request",
    startingPrice: 4000,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A 60 ft Skywalker arranged for larger day groups seeking open deck presence in Dubai.",
    fullDescription: "Infinity is considered when guest count is the priority on a shorter length. Private Luxury Holidays coordinates the enquiry with charter specialists; nothing is assumed until berth, crew and timings are confirmed.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "haigan",
    name: "Haigan",
    builder: "Harwal Marine",
    yachtType: "Motor Yacht",
    length: 90,
    lengthUnit: "ft",
    maxGuests: 20,
    cabins: 4,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 7,
    enquiryStatus: "On Request",
    startingPrice: 4000,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 4,
    shortDescription: "A 90 ft Harwal Marine yacht for considered Dubai day charters with a steadier minimum booking.",
    fullDescription: "Haigan may be requested for private coastal hours from Dubai Harbour. Her length suits mid-to-larger parties who want a quieter presence on the water. Rates and a four-hour minimum are typical reference points; final terms are confirmed on enquiry.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "aarna",
    name: "Aarna",
    builder: "Sunseeker",
    yachtType: "Motor Yacht",
    length: 90,
    lengthUnit: "ft",
    maxGuests: 20,
    cabins: 4,
    marina: "Marsa Al Arab",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 8,
    enquiryStatus: "On Request",
    startingPrice: 4000,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A Sunseeker based at Marsa Al Arab for private day charter with a different Dubai marina setting.",
    fullDescription: "Aarna is available to arrange on request through our private yacht service, departing from Marsa Al Arab. She suits travellers who want a Sunseeker day charter with a considered guest capacity. Availability and routing are confirmed with authorised partners.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "jude",
    name: "Jude",
    builder: "Sunseeker",
    yachtType: "Motor Yacht",
    length: 73,
    lengthUnit: "ft",
    maxGuests: 27,
    cabins: 4,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 9,
    enquiryStatus: "On Request",
    startingPrice: 5750,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A Sunseeker day yacht with capacity for a lively private group along the Dubai coast.",
    fullDescription: "Jude is often selected when a mid-length Sunseeker is needed for celebrations or shared coastal hours. We present her as requestable through our yacht service, not as owned inventory, and confirm every detail before travel.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "bella-iii",
    name: "Bella III",
    builder: "Ferretti",
    yachtType: "Motor Yacht",
    length: 78,
    lengthUnit: "ft",
    maxGuests: 20,
    cabins: 4,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 10,
    enquiryStatus: "On Request",
    startingPrice: 5750,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A Ferretti day charter with a composed Italian motor-yacht character for Dubai waters.",
    fullDescription: "Bella III may be arranged for private day enquiries from Dubai Harbour. Her cabins and guest capacity suit refined gatherings that still want room to move. Charter partners confirm configuration, crew and timing for each brief.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "carmen",
    name: "Carmen",
    builder: "Custom",
    yachtType: "Motor Yacht",
    length: 140,
    lengthUnit: "ft",
    maxGuests: 100,
    cabins: 3,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 11,
    enquiryStatus: "On Request",
    startingPrice: 6000,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A substantial custom yacht for large private gatherings and spacious Dubai day charters.",
    fullDescription: "Carmen is considered when guest volume defines the day. Available on request through our private yacht service, she suits corporate afternoons and larger celebrations subject to confirmation of berth, crew and minimum hours.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "straga",
    name: "Straga",
    builder: "Pershing",
    yachtType: "Motor Yacht",
    length: 82,
    lengthUnit: "ft",
    maxGuests: 15,
    cabins: 4,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 12,
    enquiryStatus: "On Request",
    startingPrice: 6500,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A Pershing day yacht for travellers who prefer a sporting, design-led motor profile.",
    fullDescription: "Straga may be requested for private Dubai Harbour charters where a more distinctive hull character is desired. Guest capacity is intentionally tighter; we match the brief carefully and confirm availability with authorised operators.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "diva",
    name: "Diva",
    builder: "Riva",
    yachtType: "Motor Yacht",
    length: 88,
    lengthUnit: "ft",
    maxGuests: 18,
    cabins: 4,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 13,
    enquiryStatus: "On Request",
    startingPrice: 7200,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "An 88 ft Riva for understated day charter with a refined motor-yacht presence.",
    fullDescription: "Diva suits private travellers seeking a Riva day on Dubai waters without excess spectacle. Through Private Luxury Holidays, access is arranged on request; rates and marina details are reconfirmed for each enquiry.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "san-lorenzo-sx88",
    name: "San Lorenzo SX88",
    builder: "San Lorenzo",
    yachtType: "Motor Yacht",
    length: 88,
    lengthUnit: "ft",
    maxGuests: 12,
    cabins: 4,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 14,
    enquiryStatus: "On Request",
    startingPrice: 7500,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A San Lorenzo SX88 for smaller, design-conscious private parties on Dubai day charter.",
    fullDescription: "The San Lorenzo SX88 is typically assessed when cabin quality and a quieter guest count matter more than maximum capacity. She may be arranged through our private yacht service subject to partner confirmation.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "dolce-vita",
    name: "Dolce Vita",
    builder: "Numarine",
    yachtType: "Motor Yacht",
    length: 105,
    lengthUnit: "ft",
    maxGuests: 20,
    cabins: 4,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 15,
    enquiryStatus: "On Request",
    startingPrice: 7900,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A Numarine yacht for composed Dubai coastal hours with a clear cabin and guest balance.",
    fullDescription: "Dolce Vita is available to arrange on request for private day charter from Dubai Harbour. She suits groups who want length and cabins without moving into the largest class. All proposals remain subject to confirmation.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "bella-viiii",
    name: "Bella VIIII",
    builder: "Ferretti",
    yachtType: "Motor Yacht",
    length: 86,
    lengthUnit: "ft",
    maxGuests: 15,
    cabins: 4,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 16,
    enquiryStatus: "On Request",
    startingPrice: 8500,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A Ferretti day yacht with a restrained guest capacity and a polished motor-yacht feel.",
    fullDescription: "Bella VIIII may be requested when a Ferretti day charter is preferred for a smaller private party. We coordinate the brief with authorised partners and do not claim ownership or guaranteed access.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "khalili",
    name: "Khalili",
    builder: "Nedship",
    yachtType: "Motor Yacht",
    length: 107,
    lengthUnit: "ft",
    maxGuests: 30,
    cabins: 4,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 17,
    enquiryStatus: "On Request",
    startingPrice: 8600,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A Nedship yacht suited to mid-to-larger Dubai day gatherings with a clear coastal presence.",
    fullDescription: "Khalili is considered for private enquiries that need more length and guest capacity than a compact day boat. Arranged on request through our yacht service, with marina and minimum hours confirmed before any commitment.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "lamborghini",
    name: "Lamborghini",
    builder: "Lamborghini",
    yachtType: "Motor Yacht",
    length: 63,
    lengthUnit: "ft",
    maxGuests: 10,
    cabins: 2,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 18,
    enquiryStatus: "On Request",
    startingPrice: 10000,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 4,
    shortDescription: "A Lamborghini day craft for smaller parties seeking a distinctive, design-led Dubai charter.",
    fullDescription: "This Lamborghini yacht is typically requested for intimate private hours rather than large gatherings. Availability, a four-hour minimum and final rates are confirmed with charter partners for each enquiry.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "stardom",
    name: "Stardom",
    builder: "Custom",
    yachtType: "Motor Yacht",
    length: 141,
    lengthUnit: "ft",
    maxGuests: 100,
    cabins: 5,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 19,
    enquiryStatus: "On Request",
    startingPrice: 10750,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A long custom yacht for substantial private gatherings and expansive Dubai day charters.",
    fullDescription: "Stardom suits briefs defined by scale—larger celebrations or corporate days that need generous guest capacity. Private Luxury Holidays can arrange an enquiry on request; confirmation rests with the operating partner.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "lucien",
    name: "Lucien",
    builder: "Sunseeker",
    yachtType: "Motor Yacht",
    length: 131,
    lengthUnit: "ft",
    maxGuests: 40,
    cabins: 7,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 20,
    enquiryStatus: "On Request",
    startingPrice: 14300,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 4,
    shortDescription: "A long Sunseeker for larger private parties and more expansive Dubai coastal hours.",
    fullDescription: "Lucien is often assessed when length, cabins and guest capacity must work together. She may be arranged through our private yacht service from Dubai Harbour, subject to a confirmed minimum booking and partner availability.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "saffuriya",
    name: "Saffuriya",
    builder: "Peri Yachts",
    yachtType: "Motor Yacht",
    length: 123,
    lengthUnit: "ft",
    maxGuests: 30,
    cabins: 5,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 21,
    enquiryStatus: "On Request",
    startingPrice: 15000,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 4,
    shortDescription: "A Peri Yachts day charter with strong length and cabin provision for considered Dubai gatherings.",
    fullDescription: "Saffuriya may be requested for private coastal hours when a longer yacht and multiple cabins are preferred. Rates and marina details are treated as reference points until confirmed for your dates.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "encore",
    name: "Encore",
    builder: "Sunseeker",
    yachtType: "Motor Yacht",
    length: 141,
    lengthUnit: "ft",
    maxGuests: 50,
    cabins: 5,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 22,
    enquiryStatus: "On Request",
    startingPrice: 15000,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A large Sunseeker for high-capacity Dubai day charter with a substantial private presence.",
    fullDescription: "Encore is considered when guest numbers and length are central to the brief. Available to arrange on request through our yacht service; we do not operate the vessel and confirm every element with authorised partners.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "thunder",
    name: "Thunder",
    builder: "Oceanfast",
    yachtType: "Motor Yacht",
    length: 164,
    lengthUnit: "ft",
    maxGuests: 35,
    cabins: 6,
    marina: "Marsa Al Arab",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 23,
    enquiryStatus: "On Request",
    startingPrice: 15500,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A long Oceanfast yacht based at Marsa Al Arab for private Dubai coastline charters.",
    fullDescription: "Thunder may be arranged on request from Marsa Al Arab when a longer yacht and larger private party are required. Routing, crew and minimum hours are confirmed case by case through our private yacht service.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "santorini",
    name: "Santorini",
    builder: "Logos",
    yachtType: "Motor Yacht",
    length: 115,
    lengthUnit: "ft",
    maxGuests: 65,
    cabins: 5,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 24,
    enquiryStatus: "On Request",
    startingPrice: 17000,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 4,
    shortDescription: "A Logos yacht with generous guest capacity for lively Dubai day gatherings.",
    fullDescription: "Santorini suits private charters where guest volume is the priority. She may be requested through Private Luxury Holidays; availability and a four-hour minimum are verified before any proposal.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "ak-royalty",
    name: "Ak Royalty",
    builder: "Palmer Johnson",
    yachtType: "Motor Yacht",
    length: 150,
    lengthUnit: "ft",
    maxGuests: 35,
    cabins: 5,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 25,
    enquiryStatus: "On Request",
    startingPrice: 17000,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 4,
    shortDescription: "A Palmer Johnson for considered Dubai day charter with length and cabin depth.",
    fullDescription: "Ak Royalty is often selected when a longer motor yacht and a refined guest capacity are needed together. Arranged on request via authorised partners; we make no ownership or exclusivity claims.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "sky-fall",
    name: "Sky Fall",
    builder: "Benetti",
    yachtType: "Motor Yacht",
    length: 164,
    lengthUnit: "ft",
    maxGuests: 50,
    cabins: 6,
    marina: "JA Marina",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 26,
    enquiryStatus: "On Request",
    startingPrice: 17200,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 4,
    shortDescription: "A Benetti based at JA Marina for substantial private Dubai day charters.",
    fullDescription: "Sky Fall may be arranged on request from JA Marina when length and guest capacity define the day. Private Luxury Holidays coordinates the enquiry; final rates, crew and timings remain subject to confirmation.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "sensation",
    name: "Sensation",
    builder: "Sensation Yachts",
    yachtType: "Motor Yacht",
    length: 164,
    lengthUnit: "ft",
    maxGuests: 25,
    cabins: 5,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 27,
    enquiryStatus: "On Request",
    startingPrice: 18000,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 6,
    shortDescription: "A long Sensation Yachts charter with a higher minimum booking for considered Dubai days.",
    fullDescription: "Sensation is typically assessed for private parties that need length and cabins with a longer minimum on the water. Available through our yacht service on request; six-hour minima and rates are confirmed for each enquiry.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "onda",
    name: "Onda",
    builder: "Custom",
    yachtType: "Motor Yacht",
    length: 105,
    lengthUnit: "ft",
    maxGuests: 100,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 28,
    enquiryStatus: "On Request",
    startingPrice: 20000,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A custom yacht arranged for very large private gatherings on Dubai day charter.",
    fullDescription: "Onda is considered when guest capacity is the primary requirement. Cabin configuration was not listed as a verified figure on the public reference used for this collection and is left blank. Access is arranged on request through authorised partners.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "behike",
    name: "Behike",
    builder: "CRN Ancona",
    yachtType: "Motor Yacht",
    length: 140,
    lengthUnit: "ft",
    maxGuests: 50,
    cabins: 5,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 29,
    enquiryStatus: "On Request",
    startingPrice: 21500,
    currency: "AED",
    pricingPeriod: "hour",
    minimumBookingHours: 3,
    shortDescription: "A CRN Ancona for high-capacity Dubai day charter with a substantial motor-yacht presence.",
    fullDescription: "Behike may be requested for private coastal hours when a longer yacht and larger party are required. Rates shown as reference are confirmed on enquiry; Private Luxury Holidays does not own or operate the vessel.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "grace",
    name: "Grace",
    builder: "Australian Yacht Builders",
    yachtType: "Motor Yacht",
    length: 196,
    lengthUnit: "ft",
    maxGuests: 60,
    cabins: 6,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 30,
    enquiryStatus: "On Request",
    pricingPeriod: "on request",
    minimumBookingHours: 24,
    shortDescription: "A long Australian-built yacht for substantial private programmes, with pricing confirmed on request.",
    fullDescription: "Grace is presented for private enquiry when length and guest capacity are paramount. Public reference pricing is POA, with an overnight-style minimum noted on the source. We arrange access on request through authorised partners and confirm every term before travel.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },
  {
    slug: "benetti-56",
    name: "Benetti 56",
    builder: "Benetti",
    yachtType: "Motor Yacht",
    length: 200,
    lengthUnit: "ft",
    maxGuests: 50,
    cabins: 6,
    marina: "Dubai Harbour",
    region: "Middle East",
    countries: ["United Arab Emirates"],
    cruisingArea: "Dubai coastline",
    displayPriority: 31,
    enquiryStatus: "On Request",
    pricingPeriod: "on request",
    minimumBookingHours: 24,
    shortDescription: "A 200 ft Benetti for the most expansive private Dubai charter briefs, priced on request.",
    fullDescription: "Benetti 56 may be arranged on request for private programmes that need flagship length and guest capacity. Pricing is POA on the public reference, with a 24-hour minimum noted. Private Luxury Holidays coordinates the enquiry without claiming ownership or guaranteed availability.",
    services: ["Day charter enquiry", "Crewed yacht arrangement", "Marina and timing coordination"],
  },

  // --- International weekly charter yachts (factual specs from Seven Yachts detail pages) ---
  {
    slug: "questa-vita",
    name: "Questa Vita",
    builder: "Mesut Uslu",
    yachtType: "Gulet",
    length: 33,
    lengthUnit: "m",
    maxGuests: 12,
    cabins: 6,
    crew: 6,
    region: "Mediterranean",
    countries: ["Turkey"],
    cruisingArea: "Turkey",
    yearBuilt: 2021,
    yearRefit: 2024,
    displayPriority: 32,
    enquiryStatus: "On Request",
    startingPrice: 22500,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 33 m Turkish gulet for composed weekly charters along the Turkish coast, with six cabins and a full crew of six.",
    fullDescription: "Questa Vita may be arranged on request through our private yacht service for travellers seeking a traditional gulet experience with contemporary comfort. Her 33-metre length and twelve-guest capacity suit families and close groups who prefer unhurried coastal weeks rather than day-hire pace. Summer and winter programmes are typically based around Turkey. Routing, crew and weekly rates are confirmed with authorised charter partners; we do not claim ownership or guaranteed availability.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "yachtiano",
    name: "Yachtiano",
    builder: "Custom",
    yachtType: "Motor Yacht",
    length: 45.5,
    lengthUnit: "m",
    maxGuests: 26,
    cabins: 13,
    crew: 7,
    region: "Red Sea",
    countries: ["Egypt"],
    cruisingArea: "Egypt",
    yearBuilt: 2024,
    displayPriority: 33,
    enquiryStatus: "On Request",
    startingPrice: 45900,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 45.5 m custom motor yacht for larger private parties in Egypt, with thirteen cabins for up to twenty-six guests.",
    fullDescription: "Yachtiano is considered when a brief calls for substantial guest capacity on Red Sea waters. Arranged on request through Private Luxury Holidays, she offers thirteen cabins and a crew of seven for weekly programmes typically based in Egypt. Exact itineraries, diving or watersport arrangements and weekly rates are reconfirmed with the charter partner before any proposal.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "bad-mutha",
    name: "Bad Mutha",
    builder: "Wally",
    yachtType: "Motor Yacht",
    length: 27,
    lengthUnit: "m",
    maxGuests: 8,
    cabins: 4,
    crew: 5,
    region: "Mediterranean",
    countries: ["Italy"],
    cruisingArea: "Italy",
    yearBuilt: 2023,
    displayPriority: 34,
    enquiryStatus: "On Request",
    startingPrice: 90000,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 27 m Wally motor yacht for intimate weekly charters in Italy, sleeping eight guests with a crew of five.",
    fullDescription: "Bad Mutha may be requested for private Mediterranean weeks when a contemporary Wally profile and a smaller guest list are preferred. Her four cabins suit couples and close friends who value design clarity over sheer scale. Summer programmes are typically arranged in Italy. Availability, crew and weekly pricing are confirmed through authorised partners.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "atalanti",
    name: "Atalanti",
    builder: "Couach",
    yachtType: "Motor Yacht",
    length: 29,
    lengthUnit: "m",
    maxGuests: 10,
    cabins: 4,
    crew: 5,
    region: "Mediterranean",
    countries: ["Croatia", "Greece", "Montenegro", "Turkey"],
    cruisingArea: "Croatia, Greece, Montenegro, Turkey",
    yearBuilt: 2004,
    yearRefit: 2017,
    displayPriority: 35,
    enquiryStatus: "On Request",
    startingPrice: 40000,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 29 m Couach motor yacht for Mediterranean weeks across Croatia, Greece, Montenegro and Turkey.",
    fullDescription: "Atalanti is typically considered for flexible Eastern Mediterranean itineraries. Built in 2004 and refitted in 2017, she accommodates ten guests in four cabins with a crew of five. Through Private Luxury Holidays she may be arranged on request; summer and winter cruising areas and weekly rates are verified for each enquiry.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "the-vision",
    name: "The Vision",
    builder: "Custom",
    yachtType: "Motor Yacht",
    length: 29,
    lengthUnit: "m",
    maxGuests: 14,
    cabins: 6,
    crew: 6,
    region: "Middle East",
    countries: ["Oman"],
    cruisingArea: "Oman",
    yearBuilt: 2025,
    displayPriority: 36,
    enquiryStatus: "On Request",
    startingPrice: 32765,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 29 m custom motor yacht for weekly private charter in Oman, with six cabins for up to fourteen guests.",
    fullDescription: "The Vision may be arranged on request for travellers seeking a private week on Omani waters. Her custom build and fourteen-guest capacity suit gatherings that need space without resorting to a larger explorer profile. Summer and winter programmes are typically based in Oman. Crewing, routing and weekly rates are confirmed with the charter partner before travel.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "b4",
    name: "B4",
    builder: "Astondoa",
    yachtType: "Motor Yacht",
    length: 32,
    lengthUnit: "m",
    maxGuests: 12,
    cabins: 6,
    crew: 5,
    region: "Mediterranean",
    countries: ["Spain"],
    cruisingArea: "Spain",
    yearBuilt: 2005,
    yearRefit: 2024,
    displayPriority: 37,
    enquiryStatus: "On Request",
    startingPrice: 76000,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 32 m Astondoa motor yacht for Spanish Mediterranean weeks, sleeping twelve across six cabins.",
    fullDescription: "B4 suits multi-generational or friendship groups who want a clear cabin plan for a Spanish coastal week. Built in 2005 and refitted in 2024, she offers twelve guests, six cabins and a crew of five. Private Luxury Holidays arranges access on request; marina timing and weekly pricing remain subject to partner confirmation.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "alvium",
    name: "Alvium",
    builder: "Custom Line",
    yachtType: "Motor Yacht",
    length: 33,
    lengthUnit: "m",
    maxGuests: 12,
    cabins: 5,
    crew: 5,
    region: "Mediterranean",
    countries: ["Spain"],
    cruisingArea: "Spain",
    yearBuilt: 2022,
    displayPriority: 38,
    enquiryStatus: "On Request",
    startingPrice: 120000,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 33 m Custom Line motor yacht for composed Spanish charter weeks, with five cabins for twelve guests.",
    fullDescription: "Alvium is considered when a contemporary Custom Line profile and open deck living are the priority for a Mediterranean week. She accommodates twelve guests in five cabins with a crew of five, typically programmed in Spain for summer and winter. Arranged on request through our yacht service, with all rates and availability confirmed before any commitment.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "l-equinox",
    name: "L'Equinox",
    builder: "Heesen",
    yachtType: "Motor Yacht",
    length: 37,
    lengthUnit: "m",
    maxGuests: 10,
    cabins: 5,
    crew: 7,
    region: "Mediterranean",
    countries: ["Greece"],
    cruisingArea: "Greece",
    yearBuilt: 2006,
    yearRefit: 2017,
    displayPriority: 39,
    enquiryStatus: "On Request",
    startingPrice: 93000,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 37 m Heesen motor yacht for Greek weekly charters, sleeping ten guests with a crew of seven.",
    fullDescription: "L'Equinox may be requested for Aegean weeks when a Heesen cabin and engineering pedigree are preferred. Built in 2006 and refitted in 2017, she offers ten guests across five cabins. Summer and winter programmes are typically based in Greece. Private Luxury Holidays coordinates the enquiry without claiming ownership or guaranteed availability.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "takara-one",
    name: "Takara One",
    builder: "Sanlorenzo",
    yachtType: "Motor Yacht",
    length: 38,
    lengthUnit: "m",
    maxGuests: 12,
    cabins: 5,
    crew: 7,
    region: "Mediterranean",
    countries: ["Greece", "Turkey"],
    cruisingArea: "Greece, Turkey",
    yearBuilt: 2016,
    yearRefit: 2020,
    displayPriority: 40,
    enquiryStatus: "On Request",
    startingPrice: 112500,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 38 m Sanlorenzo motor yacht for Greece and Turkey weeks, with twelve guests and five cabins.",
    fullDescription: "Takara One is typically assessed for Eastern Mediterranean itineraries linking Greek and Turkish waters. Her Sanlorenzo build, twelve-guest capacity and seven-person crew suit composed family and friendship weeks. Summer programmes often cover Greece and Turkey, with winter noted for Turkey on the public reference. Rates and availability are confirmed case by case.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "seahorse",
    name: "Seahorse",
    builder: "Amels",
    yachtType: "Motor Yacht",
    length: 53,
    lengthUnit: "m",
    maxGuests: 12,
    cabins: 6,
    crew: 13,
    region: "Mediterranean",
    countries: ["Greece", "Turkey"],
    cruisingArea: "Greece, Turkey",
    yearBuilt: 1999,
    yearRefit: 2019,
    displayPriority: 41,
    enquiryStatus: "On Request",
    startingPrice: 190000,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 53 m Amels motor yacht for Greece and Turkey charter weeks, sleeping twelve with a crew of thirteen.",
    fullDescription: "Seahorse may be arranged on request when a larger Dutch-built motor yacht is required for Eastern Mediterranean weeks. Built in 1999 and refitted in 2019, she accommodates twelve guests in six cabins with a crew of thirteen. Summer and winter cruising is typically noted for Greece and Turkey. All programme details remain subject to partner confirmation.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "alfa-mario",
    name: "Alfa Mario",
    builder: "Custom",
    yachtType: "Motor Yacht",
    length: 52,
    lengthUnit: "m",
    maxGuests: 32,
    cabins: 16,
    crew: 11,
    region: "Mediterranean",
    countries: ["Croatia", "Montenegro"],
    cruisingArea: "Croatia, Montenegro",
    yearBuilt: 2021,
    yearRefit: 2024,
    displayPriority: 42,
    enquiryStatus: "On Request",
    startingPrice: 110000,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 52 m custom motor yacht for large Adriatic gatherings, with sixteen cabins for up to thirty-two guests.",
    fullDescription: "Alfa Mario is considered for briefs that need unusually high guest capacity without abandoning a full-crew yacht standard. Sixteen cabins and thirty-two guests suit celebrations and multi-family weeks typically programmed in Croatia and Montenegro. Arranged on request through Private Luxury Holidays, with weekly rates and berthing confirmed before any proposal.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "kamalaya",
    name: "Kamalaya",
    builder: "Amels",
    yachtType: "Motor Yacht",
    length: 55,
    lengthUnit: "m",
    maxGuests: 10,
    cabins: 5,
    crew: 14,
    region: "Mediterranean",
    countries: ["France", "Italy", "Bahamas"],
    cruisingArea: "France, Italy",
    yearBuilt: 2013,
    yearRefit: 2025,
    displayPriority: 43,
    enquiryStatus: "On Request",
    startingPrice: 310000,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 55 m Amels motor yacht for France and Italy summer weeks, sleeping ten with a crew of fourteen.",
    fullDescription: "Kamalaya may be requested for Western Mediterranean weeks when an Amels profile and a focused ten-guest cabin plan are preferred. Built in 2013 with a 2025 refit noted on the public reference, she typically summers in France and Italy. Winter programmes may extend to the Caribbean and Bahamas depending on the season. Availability and weekly pricing are confirmed with authorised partners.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "premier",
    name: "Premier",
    builder: "Custom",
    yachtType: "Motor Yacht",
    length: 55,
    lengthUnit: "m",
    maxGuests: 22,
    cabins: 11,
    crew: 12,
    region: "Mediterranean",
    countries: ["Croatia", "Montenegro"],
    cruisingArea: "Croatia, Montenegro",
    yearBuilt: 2021,
    yearRefit: 2026,
    displayPriority: 44,
    enquiryStatus: "On Request",
    startingPrice: 87000,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 55 m custom motor yacht for Adriatic weeks, with eleven cabins for up to twenty-two guests.",
    fullDescription: "Premier suits larger private parties seeking substantial cabin count for Croatia and Montenegro. Built in 2021 with a recent refit noted for 2025–2026 on the public reference, she offers twenty-two guests and a crew of twelve. Private Luxury Holidays arranges the enquiry on request; weekly rates and itineraries are reconfirmed for each brief.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "katina",
    name: "Katina",
    builder: "Brodosplit",
    yachtType: "Motor Yacht",
    length: 60,
    lengthUnit: "m",
    maxGuests: 12,
    cabins: 6,
    crew: 15,
    region: "Mediterranean",
    countries: ["Croatia", "Greece", "Italy", "Montenegro", "Turkey"],
    cruisingArea: "Croatia, Greece, Italy, Montenegro, Turkey",
    yearBuilt: 2015,
    yearRefit: 2025,
    displayPriority: 45,
    enquiryStatus: "On Request",
    startingPrice: 245000,
    currency: "USD",
    pricingPeriod: "week",
    shortDescription: "A 60 m Brodosplit motor yacht for wide Mediterranean weeks, sleeping twelve with a crew of fifteen.",
    fullDescription: "Katina is typically considered for Eastern and Central Mediterranean programmes spanning Croatia, Greece, Italy, Montenegro and Turkey. Her sixty-metre length and twelve-guest plan suit travellers who want substantial social space without maximising cabin count. Weekly pricing is presented in USD as supplied. Arranged on request; all details confirmed with the charter partner.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "magna-grecia",
    name: "Magna Grecia",
    builder: "Elsflether Werft",
    yachtType: "Motor Yacht",
    length: 64,
    lengthUnit: "m",
    maxGuests: 12,
    cabins: 7,
    crew: 14,
    region: "Mediterranean",
    countries: ["France", "Greece", "Italy", "Malta", "Turkey", "Maldives", "Seychelles"],
    cruisingArea: "France, Greece, Italy, Malta, Turkey",
    yearBuilt: 1986,
    yearRefit: 2025,
    displayPriority: 46,
    enquiryStatus: "On Request",
    startingPrice: 329000,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 64 m Elsflether Werft motor yacht for Mediterranean summers, with seven cabins following an extensive refit.",
    fullDescription: "Magna Grecia may be arranged on request after her noted multi-year refit, for travellers seeking classic length with updated accommodation. Twelve guests, seven cabins and a crew of fourteen suit composed Mediterranean weeks across France, Greece, Italy, Malta and Turkey, with winter programmes referenced for the Maldives and Seychelles. Rates and seasonal positioning are verified before any proposal.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "la-datcha",
    name: "La Datcha",
    builder: "Damen",
    yachtType: "Explorer Yacht",
    length: 77,
    lengthUnit: "m",
    maxGuests: 12,
    cabins: 6,
    crew: 25,
    region: "Northern Europe",
    countries: ["Norway"],
    cruisingArea: "Northern Europe, Norway",
    yearBuilt: 2020,
    displayPriority: 47,
    enquiryStatus: "On Request",
    startingPrice: 750000,
    currency: "USD",
    pricingPeriod: "week",
    shortDescription: "A 77 m Damen explorer yacht for Northern European and polar-leaning programmes, sleeping twelve with a crew of twenty-five.",
    fullDescription: "La Datcha is considered when an expedition-capable yacht is required rather than a conventional coastal motor yacht. Built by Damen in 2020, she accommodates twelve guests in six cabins with a crew of twenty-five. Summer programmes are typically noted for Northern Europe and Norway, with winter referenced for Antarctica. Weekly pricing is in USD as supplied. Private Luxury Holidays coordinates the enquiry on request only.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "coral-ocean",
    name: "Coral Ocean",
    builder: "Lürssen",
    yachtType: "Motor Yacht",
    length: 73,
    lengthUnit: "m",
    maxGuests: 12,
    cabins: 7,
    crew: 22,
    region: "Mediterranean",
    countries: ["Croatia", "France", "Finland", "Norway"],
    cruisingArea: "Croatia, France, Northern Europe, Finland, Norway",
    yearBuilt: 1994,
    yearRefit: 2022,
    displayPriority: 48,
    enquiryStatus: "On Request",
    startingPrice: 650000,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 73 m Lürssen motor yacht for Adriatic and Northern European weeks, sleeping twelve after a 2022 refit.",
    fullDescription: "Coral Ocean may be requested for travellers seeking substantial Lürssen length with a refined cabin plan for twelve guests. Built in 1994 and refitted in 2022, she offers seven cabins and a crew of twenty-two. Summer cruising on the public reference spans Croatia, France and Northern Europe including Finland and Norway. Weekly rates and positioning are confirmed before any commitment.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "stella-maris",
    name: "Stella Maris",
    builder: "Viareggio Super Yacht",
    yachtType: "Motor Yacht",
    length: 72,
    lengthUnit: "m",
    maxGuests: 12,
    cabins: 7,
    crew: 19,
    region: "Mediterranean",
    countries: ["Croatia", "France", "Greece", "Italy", "Montenegro", "Turkey", "Philippines", "Thailand"],
    cruisingArea: "Croatia, France, Greece, Italy, Montenegro, Turkey",
    yearBuilt: 2015,
    yearRefit: 2025,
    displayPriority: 49,
    enquiryStatus: "On Request",
    startingPrice: 695000,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 72 m Viareggio Super Yacht motor yacht for wide Mediterranean weeks, with seven cabins for twelve guests.",
    fullDescription: "Stella Maris is typically assessed for extensive Mediterranean itineraries across Croatia, France, Greece, Italy, Montenegro and Turkey. Built in 2015 with a 2025 refit noted on the public reference, she sleeps twelve guests in seven cabins with a crew of nineteen. Arranged on request through our private yacht service; weekly pricing and seasonal routes are reconfirmed for each enquiry.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "mimtee",
    name: "Mimtee",
    builder: "CRN",
    yachtType: "Motor Yacht",
    length: 79,
    lengthUnit: "m",
    maxGuests: 12,
    cabins: 11,
    crew: 24,
    region: "Mediterranean",
    countries: ["France"],
    cruisingArea: "France",
    yearBuilt: 2019,
    displayPriority: 50,
    enquiryStatus: "On Request",
    startingPrice: 900000,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "A 79 m CRN motor yacht for French Mediterranean weeks, with eleven cabins and a crew of twenty-four.",
    fullDescription: "Mimtee may be arranged on request for private weeks when a large CRN profile and an elevated cabin count are required. Built in 2019, she accommodates twelve guests across eleven cabins with a crew of twenty-four. Summer and winter programmes are typically based in France. Rates, crew and itineraries remain subject to partner confirmation.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "chakra",
    name: "Chakra",
    builder: "Devonport",
    yachtType: "Motor Yacht",
    length: 86,
    lengthUnit: "m",
    maxGuests: 24,
    cabins: 19,
    crew: 30,
    region: "Mediterranean",
    countries: ["Croatia", "France", "Greece", "Italy", "Malta", "Montenegro", "Turkey"],
    cruisingArea: "Croatia, France, Greece, Italy, Malta, Montenegro, Turkey",
    yearBuilt: 1998,
    yearRefit: 2024,
    displayPriority: 51,
    enquiryStatus: "On Request",
    startingPrice: 495000,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "An 86 m Devonport motor yacht for large Mediterranean gatherings, sleeping twenty-four across nineteen cabins.",
    fullDescription: "Chakra is considered when a brief needs far more overnight guests than a conventional twelve-guest motor yacht. Built in 1998 and refitted in 2024, she offers twenty-four guests, nineteen cabins and a crew of thirty for wide Mediterranean programmes. Weekly rates are confirmed on request through Private Luxury Holidays; we do not claim ownership or guaranteed availability.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
  {
    slug: "arctic",
    name: "Arctic",
    builder: "Schichau Unterweser",
    yachtType: "Explorer Yacht",
    length: 88,
    lengthUnit: "m",
    maxGuests: 12,
    cabins: 7,
    crew: 28,
    region: "Northern Europe",
    // countries omitted — source lists Northern Europe only, not a specific country
    cruisingArea: "Northern Europe",
    yearBuilt: 1994,
    yearRefit: 2025,
    displayPriority: 52,
    enquiryStatus: "On Request",
    startingPrice: 490000,
    currency: "EUR",
    pricingPeriod: "week",
    shortDescription: "An 88 m explorer yacht for Northern European programmes, sleeping twelve with a crew of twenty-eight.",
    fullDescription: "Arctic may be requested for travellers seeking remote Northern European waters rather than a classic Mediterranean circuit. Built in 1994 and refitted in 2025, she accommodates twelve guests in seven cabins with a crew of twenty-eight. Summer and winter programmes are typically noted for Northern Europe. Arranged on request; all operational details are confirmed with the charter partner before travel.",
    services: ["Weekly charter enquiry", "Crewed yacht arrangement", "Itinerary coordination"],
  },
]

function deterministicId(slug: string): string {
  return `yacht-${slug}`
}

type ExistingYacht = {
  _id: string
  name?: string
  slug?: string
  builder?: string
  yachtType?: string
  length?: number
  lengthUnit?: string
  maxGuests?: number
  cabins?: number
  crew?: number
  marina?: string
  region?: string
  countries?: string[]
  cruisingArea?: string
  yearBuilt?: number
  yearRefit?: number
  displayPriority?: number
  enquiryStatus?: string
  startingPrice?: number
  currency?: string
  pricingPeriod?: string
  minimumBookingHours?: number
  shortDescription?: string
  fullDescription?: string
  amenities?: string[]
  services?: string[]
  heroImage?: unknown
  gallery?: unknown
}

function isBlank(value: unknown): boolean {
  if (value == null) return true
  if (typeof value === 'string' && value.trim() === '') return true
  if (Array.isArray(value) && value.length === 0) return true
  return false
}

async function main() {
  const existing = (await client.fetch(
    `*[_type == "yacht"]{
      _id,
      name,
      "slug": slug.current,
      builder,
      yachtType,
      length,
      lengthUnit,
      maxGuests,
      cabins,
      crew,
      marina,
      region,
      countries,
      cruisingArea,
      yearBuilt,
      yearRefit,
      displayPriority,
      enquiryStatus,
      startingPrice,
      currency,
      pricingPeriod,
      minimumBookingHours,
      shortDescription,
      fullDescription,
      amenities,
      services,
      heroImage,
      gallery
    }`,
  )) as ExistingYacht[]

  const bySlug = new Map<string, ExistingYacht[]>()
  for (const doc of existing) {
    if (!doc.slug) continue
    const list = bySlug.get(doc.slug) || []
    list.push(doc)
    bySlug.set(doc.slug, list)
  }

  const created: string[] = []
  const updated: string[] = []
  const unchanged: string[] = []
  const duplicateWarnings: string[] = []
  const missingImages: string[] = []

  for (const item of YACHTS) {
    const id = deterministicId(item.slug)
    const matches = bySlug.get(item.slug) || []

    if (matches.length > 1) {
      duplicateWarnings.push(
        `slug "${item.slug}" has ${matches.length} documents: ${matches.map((m) => m._id).join(', ')}`,
      )
    }

    const preferred = matches.find((m) => m._id === id) || matches[0] || null

    if (preferred) {
      const patch: Record<string, unknown> = {}
      if (isBlank(preferred.name)) patch.name = item.name
      if (isBlank(preferred.builder)) patch.builder = item.builder
      if (isBlank(preferred.yachtType) && item.yachtType) patch.yachtType = item.yachtType
      if (isBlank(preferred.length)) patch.length = item.length
      if (isBlank(preferred.lengthUnit)) patch.lengthUnit = item.lengthUnit
      if (isBlank(preferred.maxGuests)) patch.maxGuests = item.maxGuests
      if (isBlank(preferred.cabins) && item.cabins != null) patch.cabins = item.cabins
      if (isBlank(preferred.marina) && item.marina) patch.marina = item.marina
      if (isBlank(preferred.region) && item.region) patch.region = item.region
      if (isBlank(preferred.countries) && item.countries?.length) patch.countries = item.countries
      if (isBlank(preferred.cruisingArea) && item.cruisingArea) patch.cruisingArea = item.cruisingArea
      if (isBlank(preferred.crew) && item.crew != null) patch.crew = item.crew
      if (isBlank(preferred.yearBuilt) && item.yearBuilt != null) patch.yearBuilt = item.yearBuilt
      if (isBlank(preferred.yearRefit) && item.yearRefit != null) patch.yearRefit = item.yearRefit
      if (isBlank(preferred.displayPriority)) patch.displayPriority = item.displayPriority
      if (isBlank(preferred.enquiryStatus)) patch.enquiryStatus = item.enquiryStatus
      if (isBlank(preferred.startingPrice) && item.startingPrice != null) {
        patch.startingPrice = item.startingPrice
      }
      if (isBlank(preferred.currency) && item.currency) patch.currency = item.currency
      if (isBlank(preferred.pricingPeriod)) patch.pricingPeriod = item.pricingPeriod
      if (isBlank(preferred.minimumBookingHours) && item.minimumBookingHours != null) {
        patch.minimumBookingHours = item.minimumBookingHours
      }
      if (isBlank(preferred.shortDescription)) patch.shortDescription = item.shortDescription
      if (isBlank(preferred.fullDescription)) patch.fullDescription = item.fullDescription
      if (isBlank(preferred.services)) patch.services = item.services
      if (isBlank(preferred.amenities) && item.amenities) patch.amenities = item.amenities
      if (!preferred.slug) patch.slug = {_type: 'slug', current: item.slug}

      if (Object.keys(patch).length) {
        await client.patch(preferred._id).set(patch).commit()
        updated.push(`${item.name} (${preferred._id})`)
      } else {
        unchanged.push(`${item.name} (${preferred._id})`)
      }
      if (isBlank(preferred.heroImage)) missingImages.push(item.name)
      continue
    }

    const doc: Record<string, unknown> = {
      _id: id,
      _type: 'yacht',
      name: item.name,
      slug: {_type: 'slug', current: item.slug},
      featured: false,
      displayPriority: item.displayPriority,
      enquiryStatus: item.enquiryStatus,
      builder: item.builder,
      length: item.length,
      lengthUnit: item.lengthUnit,
      maxGuests: item.maxGuests,
      pricingPeriod: item.pricingPeriod,
      shortDescription: item.shortDescription,
      fullDescription: item.fullDescription,
      services: item.services,
      seoTitle: `${item.name} | Private Luxury Holidays`,
      seoDescription: item.shortDescription,
    }
    if (item.yachtType) doc.yachtType = item.yachtType
    if (item.cabins != null) doc.cabins = item.cabins
    if (item.crew != null) doc.crew = item.crew
    if (item.marina) doc.marina = item.marina
    if (item.region) doc.region = item.region
    if (item.countries?.length) doc.countries = item.countries
    if (item.cruisingArea) doc.cruisingArea = item.cruisingArea
    if (item.yearBuilt != null) doc.yearBuilt = item.yearBuilt
    if (item.yearRefit != null) doc.yearRefit = item.yearRefit
    if (item.startingPrice != null) doc.startingPrice = item.startingPrice
    if (item.currency) doc.currency = item.currency
    if (item.minimumBookingHours != null) doc.minimumBookingHours = item.minimumBookingHours
    if (item.amenities) doc.amenities = item.amenities

    await client.createOrReplace(doc)
    created.push(`${item.name} (${id})`)
    missingImages.push(item.name)
  }

  const after = (await client.fetch(`count(*[_type == "yacht"])`)) as number
  const seeded = (await client.fetch(
    `count(*[_type == "yacht" && string::startsWith(_id, "yacht-")])`,
  )) as number

  console.log('\n=== Yacht seed summary ===')
  console.log(`Created:   ${created.length}`)
  created.forEach((line) => console.log(`  + ${line}`))
  console.log(`Updated:   ${updated.length}`)
  updated.forEach((line) => console.log(`  ~ ${line}`))
  console.log(`Unchanged: ${unchanged.length}`)
  unchanged.forEach((line) => console.log(`  = ${line}`))
  if (duplicateWarnings.length) {
    console.log('Duplicate slugs:')
    duplicateWarnings.forEach((line) => console.log(`  ! ${line}`))
  }
  console.log(`\nYacht documents in dataset: ${after} (seeded yacht-* ids: ${seeded})`)
  console.log(`\nYachts needing licensed imagery (${missingImages.length}):`)
  missingImages.forEach((name) => console.log(`  - ${name}`))
  console.log('\nNote: heroImage left empty deliberately. Upload licensed photos in Studio.')
  console.log('Home marina left blank for international yachts unless a verified berth is known.')
  console.log('Countries filled from verified charter destinations only (not broad regions).')
  console.log('Region retained for internal use; Country is the primary website filter.')
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
