import {defineField, defineType} from 'sanity'

const enquiryStatusList = [
  {title: 'Available', value: 'Available'},
  {title: 'On Request', value: 'On Request'},
  {title: 'Enquire', value: 'Enquire'},
]

export const yacht = defineType({
  name: 'yacht',
  title: 'Yacht',
  type: 'document',
  groups: [
    {name: 'basics', title: 'Basics', default: true},
    {name: 'media', title: 'Media'},
    {name: 'vessel', title: 'Vessel'},
    {name: 'details', title: 'Details'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'name',
      title: 'Name',
      type: 'string',
      group: 'basics',
      description: 'Yacht name as shown on the website.',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'basics',
      description: 'URL-safe identifier. Click Generate from the name.',
      options: {source: 'name', maxLength: 96},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'featured',
      title: 'Featured',
      type: 'boolean',
      group: 'basics',
      description: 'Enable this to highlight the yacht in featured collections.',
      initialValue: false,
    }),
    defineField({
      name: 'displayPriority',
      title: 'Display priority',
      type: 'number',
      group: 'basics',
      description: 'Lower numbers appear first in the collection. Example: 1 appears before 2.',
      validation: (Rule) => Rule.min(0).integer(),
    }),
    defineField({
      name: 'enquiryStatus',
      title: 'Enquiry status',
      type: 'string',
      group: 'basics',
      description: 'Availability label shown for enquiries.',
      options: {list: enquiryStatusList, layout: 'dropdown'},
    }),
    defineField({
      name: 'heroImage',
      title: 'Hero image',
      type: 'image',
      group: 'media',
      description: 'Primary image used on the yacht card and presentation.',
      options: {hotspot: true},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'gallery',
      title: 'Gallery',
      type: 'array',
      group: 'media',
      description: 'Additional images shown in the gallery. Drag to reorder.',
      of: [{type: 'image', options: {hotspot: true}}],
    }),
    defineField({
      name: 'yachtType',
      title: 'Yacht type',
      type: 'string',
      group: 'vessel',
      description: 'For example Motor Yacht, Sailing Yacht, Catamaran.',
    }),
    defineField({
      name: 'length',
      title: 'Length',
      type: 'number',
      group: 'vessel',
      description: 'Length as a number only. Choose the unit below.',
      validation: (Rule) => Rule.min(0),
    }),
    defineField({
      name: 'lengthUnit',
      title: 'Length unit',
      type: 'string',
      group: 'vessel',
      options: {
        list: [
          {title: 'm', value: 'm'},
          {title: 'ft', value: 'ft'},
        ],
        layout: 'dropdown',
      },
    }),
    defineField({
      name: 'cabins',
      title: 'Cabins',
      type: 'number',
      group: 'vessel',
      validation: (Rule) => Rule.min(0).integer(),
    }),
    defineField({
      name: 'maxGuests',
      title: 'Maximum guests',
      type: 'number',
      group: 'vessel',
      validation: (Rule) => Rule.min(0).integer(),
    }),
    defineField({
      name: 'crew',
      title: 'Crew',
      type: 'number',
      group: 'vessel',
      description: 'Typical crew size.',
      validation: (Rule) => Rule.min(0).integer(),
    }),
    defineField({
      name: 'cruisingArea',
      title: 'Location / cruising area',
      type: 'string',
      group: 'vessel',
      description: 'Primary region or cruising area.',
    }),
    defineField({
      name: 'shortDescription',
      title: 'Short description',
      type: 'text',
      group: 'details',
      rows: 3,
    }),
    defineField({
      name: 'fullDescription',
      title: 'Full description',
      type: 'text',
      group: 'details',
      rows: 8,
    }),
    defineField({
      name: 'amenities',
      title: 'Amenities',
      type: 'array',
      group: 'details',
      description: 'Onboard amenities. Press Enter after each.',
      of: [{type: 'string'}],
      options: {layout: 'tags'},
    }),
    defineField({
      name: 'services',
      title: 'Services',
      type: 'array',
      group: 'details',
      description: 'Optional services. Press Enter after each.',
      of: [{type: 'string'}],
      options: {layout: 'tags'},
    }),
    defineField({
      name: 'seoTitle',
      title: 'SEO title',
      type: 'string',
      group: 'seo',
    }),
    defineField({
      name: 'seoDescription',
      title: 'SEO description',
      type: 'text',
      group: 'seo',
      rows: 3,
    }),
  ],
  orderings: [
    {
      title: 'Display priority',
      name: 'displayPriorityAsc',
      by: [
        {field: 'displayPriority', direction: 'asc'},
        {field: 'name', direction: 'asc'},
      ],
    },
    {
      title: 'Name',
      name: 'nameAsc',
      by: [{field: 'name', direction: 'asc'}],
    },
  ],
  preview: {
    select: {
      title: 'name',
      media: 'heroImage',
      yachtType: 'yachtType',
      cabins: 'cabins',
      maxGuests: 'maxGuests',
      featured: 'featured',
    },
    prepare({title, media, yachtType, cabins, maxGuests, featured}) {
      const parts = [
        yachtType,
        cabins != null ? `${cabins} Cabins` : null,
        maxGuests != null ? `${maxGuests} Guests` : null,
      ].filter(Boolean)
      return {
        title: featured && title ? `${title} ★` : title || 'Untitled yacht',
        subtitle: parts.length ? parts.join(' · ') : undefined,
        media,
      }
    },
  },
})
